#!/usr/bin/expect -f

set user "sss@ftp1.aqualine.jp"
set password "hZuBewLvSLh1#"
#「 アクアライン 」sftpサーバーにログインします。
spawn sftp "$user"
expect "assword:" { send "$password\r" }
expect "sftp>" { send "cd hon/import\r" }
foreach arg $argv {
    #「アクアライン 」sftpサーバーからファイルをフェッチします。
    expect "sftp>" { send "get $arg\r" }
    # ファイルを「/ done」ディレクトリに移動します。
    expect "sftp>" { send "rename $arg /hon/import/done/$arg\r" }
}
expect "sftp>"
send "exit\r";
expect eof